# SPDX-License-Identifier: MIT
# Copyright (c) 2019 Gennady Trafimenkov

FROM ubuntu:16.04

RUN apt-get update \
  && echo "== security updates" \
  && apt-get install --no-install-recommends -y $(apt-get -s dist-upgrade | grep -i security | cut -f2 -d\ | sort | uniq) \
  && echo "== additional soft" \
  && apt-get install -y \
    apt-transport-https \
    curl \
  && echo "== cleanup" \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && echo "== done"
